# Generated by Django 5.0.4 on 2024-06-23 15:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=64, unique=True)),
                ('thong_tin', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoUong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=64, unique=True)),
                ('anh', models.ImageField(blank=True, null=True, upload_to='do_uong/%Y/%m')),
                ('thong_tin', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('so_luong', models.IntegerField()),
                ('don_gia', models.IntegerField()),
                ('danh_muc', models.ManyToManyField(blank=True, to='sweet.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('giam_gia', models.IntegerField(blank=True, null=True)),
                ('tong_tien', models.IntegerField()),
                ('do_uong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sweet.douong')),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh', models.ImageField(blank=True, null=True, upload_to='khach_hang/%Y/%m')),
                ('ten', models.CharField(max_length=128)),
                ('tuoi', models.IntegerField()),
                ('gioi_tinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('sdt', models.CharField(blank=True, max_length=12, null=True)),
                ('dia_chi', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('gio_hang', models.ManyToManyField(blank=True, to='sweet.giohang')),
            ],
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_mua', models.DateField(auto_now_add=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('tong_tien', models.IntegerField()),
                ('giam_gia', models.IntegerField(blank=True, null=True)),
                ('do_uong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sweet.douong')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sweet.khachhang')),
            ],
        ),
    ]
