# Generated by Django 5.0.4 on 2024-07-16 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0002_alter_douong_don_gia_alter_douong_so_luong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='gio_hang',
        ),
        migrations.AddField(
            model_name='khachhang',
            name='gio_hang',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sweet.giohang'),
        ),
    ]
