# Generated by Django 5.0.4 on 2024-07-16 03:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0003_remove_khachhang_gio_hang_khachhang_gio_hang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giohang',
            name='do_uong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sweet.douong'),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='so_luong',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='tong_tien',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
