# Generated by Django 5.0.4 on 2024-07-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0006_alter_khachhang_ten_alter_khachhang_tuoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='gioi_tinh',
            field=models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, null=True),
        ),
    ]
