# Generated by Django 5.0.4 on 2024-08-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0009_remove_giohangdouong_giam_gia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thanhtoan',
            name='giam_gia',
        ),
    ]
